<?php
/**
 * @file
 * Context Datalayer Module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function context_datalayer_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_theme().
 */
function context_datalayer_theme() {
  return array(
    'context_datalayer_form' => array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_datalayer_alter().
 */
function context_datalayer_datalayer_alter(&$datalayer) {
  if ($plugin = context_get_plugin('condition', 'context_datalayer_condition')) {
    $plugin->execute($datalayer);
  }
  if ($plugin = context_get_plugin('reaction', 'context_datalayer_reaction')) {
    $plugin->execute($datalayer);
  }
}

/**
 * Implements hook_context_plugins().
 */
function context_datalayer_context_plugins() {
  return array(
    'context_datalayer_condition' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'context_datalayer') . '/plugins',
        'file' => 'context_datalayer_condition.inc',
        'class' => 'context_datalayer_condition',
        'parent' => 'context_condition',
      ),
    ),
    'context_datalayer_reaction' => array(
      'handler' => array(
        'path' => drupal_get_path('module', 'context_datalayer') . '/plugins',
        'file' => 'context_datalayer_reaction.inc',
        'class' => 'context_datalayer_reaction',
        'parent' => 'context_reaction',
      ),
    ),
  );
}

/**
 * Implements hook_context_registry().
 */
function context_datalayer_context_registry() {
  return array(
    'conditions' => array(
      'context_datalayer_condition' => array(
        'title' => t('Data Layer'),
        'description' => t('React to the Data Layer using context.'),
        'plugin' => 'context_datalayer_condition',
      ),
    ),
    'reactions' => array(
      'context_datalayer_reaction' => array(
        'title' => t('Data Layer'),
        'description' => t('Adjust the Data Layer using context.'),
        'plugin' => 'context_datalayer_reaction',
      ),
    ),
  );
}

/**
 * Theme callback for context options form.
 */
function theme_context_datalayer_form($variables) {
  $form = $variables['form'];
  $rows = array();

  foreach (element_children($form['context_datalayer']) as $key) {
    $rows[] = array(
      'data' => array(
        render($form['context_datalayer'][$key]),
        render($form['types'][$key]),
        render($form['values'][$key]),
        render($form['remove'][$key]),
      ),
    );
  }

  $form['add']['#attributes'] = array('class' => array('container-inline'));
  $title = $form['add']['key']['#title'];
  $description = $form['add']['key']['#description'];
  unset($form['add']['key']['#title']);
  unset($form['add']['key']['#description']);

  $output = theme('table', array(
    'header' => array(
      array(
        'data' => t('Key Value Pairs'),
        'colspan' => 3,
      ),
      t('Operations'),
    ),
    'rows' => $rows,
    'empty' => t('No data has been entered yet.'),
  ));
  $output .= '<h2>' . $title . '</h2>';
  $output .= render($form['add']);
  $output .= $description;
  $output .= drupal_render_children($form);

  return $output;
}
