<?php
/**
 * @file
 * Context Datalayer Module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function context_datalayer_ctools_plugin_api($module, $api) {
  if ($module == 'context' && $api == 'plugins') {
    return array('version' => 3);
  }
}

/**
 * Implements hook_theme().
 */
function context_datalayer_theme() {
  return array(
    'context_datalayer_form'=> array(
      'render element' => 'form',
    ),
  );
}

/**
 * Implements hook_context_page_reaction().
 */
function context_datalayer_context_page_reaction() {
  ctools_include('context_datalayer_reaction', 'context_datalayer', 'plugins');
  if ($plugin = context_get_plugin('reaction', 'context_datalayer')) {
    $plugin->execute();
  }
}

/**
 * Implements hook_context_plugins().
 */
function context_datalayer_context_plugins() {
  $plugins = array();
  $plugins['context_datalayer_reaction'] = array(
    'handler' => array(
      'path' => drupal_get_path('module', 'context_datalayer') . '/plugins',
      'file' => 'context_datalayer_reaction.inc',
      'class' => 'context_datalayer_reaction',
      'parent' => 'context_reaction',
    ),
  );
  return $plugins;
}

/**
 * Implements hook_context_registry().
 */
function context_datalayer_context_registry() {
  return array(
    'reactions' => array(
      'context_datalayer' => array(
        'title' => t('Data Layer'),
        'description' => t('Adjust the Data Layer using context.'),
        'plugin' => 'context_datalayer_reaction',
      ),
    ),
  );
}

/**
 * Theme callback for context options form.
 */
function theme_context_datalayer_form($variables) {
  $form = $variables['form'];
  $rows = array();

  foreach (element_children($form['context_datalayer']) as $class) {
    $rows[] = array(
      'data' => array(
        render($form['context_datalayer'][$class]),
        render($form['remove'][$class]),
      ),
    );
  }

  return theme('table', array(
    'header' => array(t('Section Classes'), t('Operations')),
    'rows' => $rows,
    'empty' => t('No classes have been added.'),
  )) . render($form['add']);
}
